//! Axum route handlers for a Maven repository read + deploy surface.
//!
//! Supported operations:
//! - `GET .../maven-metadata.xml`
//! - `GET .../*.sha256`
//! - `GET` artifact download (for example `.jar`, `.pom`, `.module`, `.asc`)
//! - `PUT /maven/{groupPath}/{artifactId}/{version}/{filename}`

use axum::{
    body::Body,
    extract::{DefaultBodyLimit, Path, State},
    http::{
        header::{AUTHORIZATION, CONTENT_DISPOSITION, CONTENT_LENGTH, CONTENT_TYPE},
        HeaderMap, StatusCode,
    },
    response::{IntoResponse, Response},
    routing::get,
    Router,
};
use base64::{engine::general_purpose::STANDARD as BASE64_STANDARD, Engine as _};
use bytes::Bytes;
use chrono::{DateTime, Duration, Utc};
use sqlx::{PgPool, Row};
use uuid::Uuid;

use publaryn_core::{
    domain::{namespace::Ecosystem, package::normalize_package_name},
    error::Error,
};

use crate::{
    metadata::{build_maven_metadata_xml, MavenMetadataInput},
    name::{package_name, parse_artifact_path, parse_metadata_path},
    publish::{self, ParsedMavenUpload},
};

const MAVEN_PUBLISH_GRACE_WINDOW_HOURS: i64 = 1;
const ORG_PACKAGE_WRITE_ROLES: &[&str] = &["owner", "admin", "maintainer", "publisher"];
const TEAM_PACKAGE_PUBLISH_PERMISSIONS: &[&str] = &["admin", "publish"];
const TEAM_REPOSITORY_PUBLISH_PERMISSIONS: &[&str] = &["admin", "publish"];

pub trait MavenAppState: Clone + Send + Sync + 'static {
    fn db(&self) -> &PgPool;
    fn artifact_put(
        &self,
        key: String,
        content_type: String,
        bytes: Bytes,
    ) -> impl std::future::Future<Output = Result<(), Error>> + Send;
    fn artifact_get(
        &self,
        key: &str,
    ) -> impl std::future::Future<Output = Result<Option<StoredObject>, Error>> + Send;
    fn jwt_secret(&self) -> &str;
    fn jwt_issuer(&self) -> &str;
}

#[derive(Debug, Clone)]
pub struct StoredObject {
    pub content_type: String,
    pub bytes: Bytes,
}

#[derive(Debug, Clone)]
struct MavenIdentity {
    user_id: Uuid,
    token_id: Option<Uuid>,
    scopes: Vec<String>,
}

#[derive(Debug, Clone)]
struct ReleaseUploadContext {
    release_id: Uuid,
    status: String,
    published_at: DateTime<Utc>,
    created: bool,
}

pub fn router<S: MavenAppState>() -> Router<S> {
    Router::new()
        .route(
            "/{*path}",
            get(repository_get::<S>).put(repository_put::<S>),
        )
        .layer(DefaultBodyLimit::disable())
}

async fn repository_get<S: MavenAppState>(
    State(state): State<S>,
    Path(path): Path<String>,
    headers: HeaderMap,
) -> Response {
    if path.ends_with("/maven-metadata.xml") {
        return metadata_get(state, path, headers).await;
    }

    if let Some(stripped) = path.strip_suffix(".sha256") {
        return checksum_get(state, stripped.to_owned(), headers).await;
    }

    artifact_get(state, path, headers).await
}

async fn repository_put<S: MavenAppState>(
    State(state): State<S>,
    Path(path): Path<String>,
    headers: HeaderMap,
    body: Bytes,
) -> Response {
    if path.ends_with("/maven-metadata.xml") {
        return bad_request_response(
            "maven-metadata.xml is generated by Publaryn and cannot be uploaded directly",
        );
    }

    let identity = match authenticate_publish_required(&state, &headers).await {
        Ok(identity) => identity,
        Err(response) => return response,
    };

    if !has_scope(&identity, "packages:write") {
        return forbidden_response("Token does not have the packages:write scope");
    }

    let (group_id, artifact_id, version, filename) = match parse_artifact_path(&path) {
        Ok(parsed) => parsed,
        Err(error) => return bad_request_response(&error.to_string()),
    };

    let upload =
        match publish::parse_maven_upload(&group_id, &artifact_id, &version, &filename, body) {
            Ok(upload) => upload,
            Err(error) => return bad_request_response(&error.to_string()),
        };

    let package_id = match resolve_or_create_package(&state, &identity, &upload).await {
        Ok(package_id) => package_id,
        Err(response) => return response,
    };

    let release =
        match resolve_or_create_release(state.db(), package_id, &upload, identity.user_id).await {
            Ok(release) => release,
            Err(response) => return response,
        };

    if let Some(target_filename) = upload.target_filename() {
        if let Err(response) =
            ensure_target_artifact_exists(state.db(), release.release_id, target_filename, &upload)
                .await
        {
            return response;
        }
    }

    let existing_artifact =
        match sqlx::query("SELECT sha256 FROM artifacts WHERE release_id = $1 AND filename = $2")
            .bind(release.release_id)
            .bind(&upload.filename)
            .fetch_optional(state.db())
            .await
        {
            Ok(row) => row,
            Err(_) => return internal_error_response("Database error"),
        };

    if let Some(existing_artifact) = existing_artifact {
        let existing_sha256: String = existing_artifact.try_get("sha256").unwrap_or_default();
        if existing_sha256 != upload.sha256 {
            return conflict_response(&format!(
                "An artifact named '{}' already exists for Maven release '{}' with different content",
                upload.filename, upload.version,
            ));
        }

        if let Err(response) =
            apply_post_upload_updates(state.db(), &identity, package_id, &release, &upload, false)
                .await
        {
            return response;
        }

        return (StatusCode::OK, "").into_response();
    }

    if !release_accepts_new_artifacts(&release) {
        return conflict_response(&format!(
            "Maven release '{}' is finalized and no longer accepts new artifacts",
            upload.version,
        ));
    }

    let artifact = publish::make_artifact(release.release_id, &upload);
    if state
        .artifact_put(
            artifact.storage_key.clone(),
            artifact.content_type.clone(),
            upload.bytes.clone(),
        )
        .await
        .is_err()
    {
        if release.created {
            let _ = sqlx::query("DELETE FROM releases WHERE id = $1")
                .bind(release.release_id)
                .execute(state.db())
                .await;
        }

        return internal_error_response("Failed to store Maven artifact");
    }

    let insert_result = match sqlx::query(
        "INSERT INTO artifacts (id, release_id, kind, filename, storage_key, content_type, size_bytes, sha256, sha512, md5, is_signed, signature_key_id, uploaded_at) \
         VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, NULL, $10, NULL, $11) \
         ON CONFLICT (release_id, filename) DO NOTHING",
    )
    .bind(artifact.id)
    .bind(artifact.release_id)
    .bind(artifact.kind.clone())
    .bind(&artifact.filename)
    .bind(&artifact.storage_key)
    .bind(&artifact.content_type)
    .bind(artifact.size_bytes)
    .bind(&artifact.sha256)
    .bind(&artifact.sha512)
    .bind(matches!(artifact.kind, publaryn_core::domain::artifact::ArtifactKind::Signature))
    .bind(artifact.uploaded_at)
    .execute(state.db())
    .await
    {
        Ok(result) => result,
        Err(_) => return internal_error_response("Failed to record Maven artifact"),
    };

    if insert_result.rows_affected() == 0 {
        let existing_artifact = match sqlx::query(
            "SELECT sha256 FROM artifacts WHERE release_id = $1 AND filename = $2",
        )
        .bind(release.release_id)
        .bind(&upload.filename)
        .fetch_optional(state.db())
        .await
        {
            Ok(Some(row)) => row,
            Ok(None) => {
                return internal_error_response(
                    "Artifact insert conflicted but no stored Maven artifact could be reloaded",
                )
            }
            Err(_) => return internal_error_response("Database error"),
        };

        let existing_sha256: String = existing_artifact.try_get("sha256").unwrap_or_default();
        if existing_sha256 != upload.sha256 {
            return conflict_response(&format!(
                "An artifact named '{}' already exists for Maven release '{}' with different content",
                upload.filename, upload.version,
            ));
        }

        if let Err(response) =
            apply_post_upload_updates(state.db(), &identity, package_id, &release, &upload, false)
                .await
        {
            return response;
        }

        return (StatusCode::OK, "").into_response();
    }

    if let Err(response) =
        apply_post_upload_updates(state.db(), &identity, package_id, &release, &upload, true).await
    {
        return response;
    }

    (StatusCode::CREATED, "").into_response()
}

async fn metadata_get<S: MavenAppState>(state: S, path: String, headers: HeaderMap) -> Response {
    let identity = match authenticate_optional(&state, &headers).await {
        Ok(identity) => identity,
        Err(response) => return response,
    };
    let actor_user_id = identity.as_ref().map(|identity| identity.user_id);

    let (group_id, artifact_id) = match parse_metadata_path(&path) {
        Ok(parsed) => parsed,
        Err(_) => return not_found_response("Artifact metadata not found"),
    };
    let package_name = match package_name(&group_id, &artifact_id) {
        Ok(name) => name,
        Err(_) => return not_found_response("Artifact metadata not found"),
    };

    let package_row = match load_package_row(state.db(), &package_name).await {
        Ok(row) => row,
        Err(response) => return response,
    };

    if !package_readable(&package_row, state.db(), actor_user_id).await {
        return not_found_response("Artifact metadata not found");
    }

    let package_id: Uuid = match package_row.try_get("id") {
        Ok(id) => id,
        Err(_) => return internal_error_response("Internal error"),
    };

    let release_rows = match sqlx::query(
        "SELECT version, published_at \
         FROM releases \
         WHERE package_id = $1 AND status IN ('published', 'deprecated', 'yanked') \
         ORDER BY published_at DESC, version DESC",
    )
    .bind(package_id)
    .fetch_all(state.db())
    .await
    {
        Ok(rows) => rows,
        Err(_) => return internal_error_response("Database error"),
    };

    if release_rows.is_empty() {
        return not_found_response("Artifact metadata not found");
    }

    let versions = release_rows
        .iter()
        .filter_map(|row| row.try_get::<String, _>("version").ok())
        .collect::<Vec<_>>();
    let latest = versions.first().cloned();
    let last_updated = release_rows
        .first()
        .and_then(|row| row.try_get("published_at").ok())
        .unwrap_or_else(Utc::now);

    let xml = build_maven_metadata_xml(&MavenMetadataInput {
        group_id,
        artifact_id,
        latest: latest.clone(),
        release: latest,
        versions,
        last_updated,
    });

    (
        StatusCode::OK,
        [(CONTENT_TYPE, "application/xml; charset=utf-8")],
        xml,
    )
        .into_response()
}

async fn checksum_get<S: MavenAppState>(state: S, path: String, headers: HeaderMap) -> Response {
    let identity = match authenticate_optional(&state, &headers).await {
        Ok(identity) => identity,
        Err(response) => return response,
    };
    let actor_user_id = identity.as_ref().map(|identity| identity.user_id);

    let (group_id, artifact_id, version, filename) = match parse_artifact_path(&path) {
        Ok(parsed) => parsed,
        Err(_) => return not_found_response("Checksum not found"),
    };

    let package_name = match package_name(&group_id, &artifact_id) {
        Ok(name) => name,
        Err(_) => return not_found_response("Checksum not found"),
    };

    let artifact_row = match load_artifact_row(state.db(), &package_name, &version, &filename).await
    {
        Ok(row) => row,
        Err(response) => return response,
    };

    if !artifact_readable(&artifact_row, state.db(), actor_user_id).await {
        return not_found_response("Checksum not found");
    }

    let sha256: String = artifact_row.try_get("sha256").unwrap_or_default();
    (
        StatusCode::OK,
        [(CONTENT_TYPE, "text/plain; charset=utf-8")],
        format!("{sha256}\n"),
    )
        .into_response()
}

async fn artifact_get<S: MavenAppState>(state: S, path: String, headers: HeaderMap) -> Response {
    let identity = match authenticate_optional(&state, &headers).await {
        Ok(identity) => identity,
        Err(response) => return response,
    };
    let actor_user_id = identity.as_ref().map(|identity| identity.user_id);

    let (group_id, artifact_id, version, filename) = match parse_artifact_path(&path) {
        Ok(parsed) => parsed,
        Err(_) => return not_found_response("Artifact not found"),
    };

    let package_name = match package_name(&group_id, &artifact_id) {
        Ok(name) => name,
        Err(_) => return not_found_response("Artifact not found"),
    };

    let artifact_row = match load_artifact_row(state.db(), &package_name, &version, &filename).await
    {
        Ok(row) => row,
        Err(response) => return response,
    };

    if !artifact_readable(&artifact_row, state.db(), actor_user_id).await {
        return not_found_response("Artifact not found");
    }

    let storage_key: String = artifact_row.try_get("storage_key").unwrap_or_default();
    let sha256: String = artifact_row.try_get("sha256").unwrap_or_default();
    let stored = match state.artifact_get(&storage_key).await {
        Ok(Some(stored)) => stored,
        Ok(None) => return not_found_response("Artifact not found"),
        Err(_) => return internal_error_response("Artifact storage error"),
    };

    let package_id: Uuid = artifact_row.try_get("package_id").unwrap_or(Uuid::nil());
    let _ = sqlx::query("UPDATE packages SET download_count = download_count + 1 WHERE id = $1")
        .bind(package_id)
        .execute(state.db())
        .await;

    let content_type = if stored.content_type.is_empty() {
        artifact_row
            .try_get::<String, _>("content_type")
            .unwrap_or_else(|_| "application/octet-stream".into())
    } else {
        stored.content_type
    };
    let disposition = format!("attachment; filename=\"{}\"", filename.replace('"', ""));

    Response::builder()
        .status(StatusCode::OK)
        .header(CONTENT_TYPE, content_type)
        .header(CONTENT_LENGTH, stored.bytes.len().to_string())
        .header(CONTENT_DISPOSITION, disposition)
        .header("x-checksum-sha256", sha256)
        .body(Body::from(stored.bytes))
        .unwrap_or_else(|_| internal_error_response("Internal error"))
}

async fn resolve_or_create_package<S: MavenAppState>(
    state: &S,
    identity: &MavenIdentity,
    upload: &ParsedMavenUpload,
) -> Result<Uuid, Response> {
    let normalized_name = normalize_package_name(&upload.package_name, &Ecosystem::Maven);
    let existing_package = match sqlx::query(
        "SELECT id, repository_id, owner_user_id, owner_org_id \
         FROM packages \
         WHERE ecosystem = 'maven' AND normalized_name = $1",
    )
    .bind(&normalized_name)
    .fetch_optional(state.db())
    .await
    {
        Ok(row) => row,
        Err(_) => return Err(internal_error_response("Database error")),
    };

    match existing_package {
        Some(row) => {
            let package_id: Uuid = row.try_get("id").unwrap_or_default();
            let repository_id: Uuid = row.try_get("repository_id").unwrap_or_default();
            if !has_package_write_access(
                state.db(),
                package_id,
                repository_id,
                row.try_get("owner_user_id").unwrap_or(None),
                row.try_get("owner_org_id").unwrap_or(None),
                identity.user_id,
            )
            .await
            {
                return Err(forbidden_response(
                    "You do not have permission to publish to this Maven package",
                ));
            }

            Ok(package_id)
        }
        None => {
            if !upload.can_start_release() {
                return Err(conflict_response(
                    "Maven checksum and signature uploads require the target artifact to exist first",
                ));
            }

            auto_create_package(state, identity, upload).await
        }
    }
}

async fn auto_create_package<S: MavenAppState>(
    state: &S,
    identity: &MavenIdentity,
    upload: &ParsedMavenUpload,
) -> Result<Uuid, Response> {
    let repository = match publish::select_default_repository(state.db(), identity.user_id).await {
        Ok(repository) => repository,
        Err(Error::Forbidden(message)) => return Err(forbidden_response(&message)),
        Err(_) => {
            return Err(internal_error_response(
                "Failed to resolve a repository for Maven deploy",
            ))
        }
    };

    validate_namespace_claim_for_group_id(
        state.db(),
        &upload.group_id,
        repository.owner_user_id,
        repository.owner_org_id,
    )
    .await?;

    let package_id = Uuid::new_v4();
    let now = Utc::now();
    let insert_result = sqlx::query(
        "INSERT INTO packages (id, repository_id, ecosystem, name, normalized_name, display_name, description, readme, homepage, repository_url, license, keywords, visibility, owner_user_id, owner_org_id, is_deprecated, deprecation_message, is_archived, download_count, created_at, updated_at) \
         VALUES ($1, $2, 'maven', $3, $4, $5, $6, NULL, $7, $8, $9, $10, $11, $12, $13, false, NULL, false, 0, $14, $15)",
    )
    .bind(package_id)
    .bind(repository.id)
    .bind(&upload.package_name)
    .bind(normalize_package_name(&upload.package_name, &Ecosystem::Maven))
    .bind(upload.pom_display_name())
    .bind(upload.pom_description())
    .bind(upload.pom_homepage())
    .bind(upload.pom_repository_url())
    .bind(upload.pom_primary_license())
    .bind(Vec::<String>::new())
    .bind(repository.visibility.as_str())
    .bind(repository.owner_user_id)
    .bind(repository.owner_org_id)
    .bind(now)
    .bind(now)
    .execute(state.db())
    .await;

    match insert_result {
        Ok(_) => {
            let _ = sqlx::query(
                "INSERT INTO audit_logs (id, action, actor_user_id, actor_token_id, target_package_id, metadata, occurred_at) \
                 VALUES ($1, 'package_create', $2, $3, $4, $5, NOW())",
            )
            .bind(Uuid::new_v4())
            .bind(identity.user_id)
            .bind(identity.token_id)
            .bind(package_id)
            .bind(serde_json::json!({
                "ecosystem": "maven",
                "name": upload.package_name,
                "source": "maven_deploy",
            }))
            .execute(state.db())
            .await;

            Ok(package_id)
        }
        Err(sqlx::Error::Database(db_error)) if db_error.is_unique_violation() => {
            let existing = sqlx::query(
                "SELECT id, repository_id, owner_user_id, owner_org_id \
                 FROM packages \
                 WHERE ecosystem = 'maven' AND normalized_name = $1",
            )
            .bind(normalize_package_name(
                &upload.package_name,
                &Ecosystem::Maven,
            ))
            .fetch_optional(state.db())
            .await
            .map_err(|_| internal_error_response("Failed to reload Maven package"))?
            .ok_or_else(|| internal_error_response("Failed to reload Maven package"))?;

            let package_id: Uuid = existing.try_get("id").unwrap_or_default();
            let repository_id: Uuid = existing.try_get("repository_id").unwrap_or_default();
            if !has_package_write_access(
                state.db(),
                package_id,
                repository_id,
                existing.try_get("owner_user_id").unwrap_or(None),
                existing.try_get("owner_org_id").unwrap_or(None),
                identity.user_id,
            )
            .await
            {
                return Err(forbidden_response(
                    "You do not have permission to publish to this Maven package",
                ));
            }

            Ok(package_id)
        }
        Err(_) => Err(internal_error_response("Failed to create Maven package")),
    }
}

async fn validate_namespace_claim_for_group_id(
    db: &PgPool,
    group_id: &str,
    owner_user_id: Option<Uuid>,
    owner_org_id: Option<Uuid>,
) -> Result<(), Response> {
    let row = match sqlx::query(
        "SELECT owner_user_id, owner_org_id \
         FROM namespace_claims \
         WHERE ecosystem = 'maven'::ecosystem AND namespace = $1",
    )
    .bind(group_id)
    .fetch_optional(db)
    .await
    {
        Ok(row) => row,
        Err(_) => return Err(internal_error_response("Database error")),
    };

    let Some(row) = row else {
        return Ok(());
    };

    let claim_owner_user_id = row
        .try_get::<Option<Uuid>, _>("owner_user_id")
        .unwrap_or(None);
    let claim_owner_org_id = row
        .try_get::<Option<Uuid>, _>("owner_org_id")
        .unwrap_or(None);
    if claim_owner_user_id != owner_user_id || claim_owner_org_id != owner_org_id {
        return Err(forbidden_response(&format!(
            "Namespace '{}' is claimed by another owner",
            group_id,
        )));
    }

    Ok(())
}

async fn resolve_or_create_release(
    db: &PgPool,
    package_id: Uuid,
    upload: &ParsedMavenUpload,
    actor_user_id: Uuid,
) -> Result<ReleaseUploadContext, Response> {
    let existing_release = match sqlx::query(
        "SELECT id, status::text AS status, published_at \
         FROM releases \
         WHERE package_id = $1 AND version = $2",
    )
    .bind(package_id)
    .bind(&upload.version)
    .fetch_optional(db)
    .await
    {
        Ok(row) => row,
        Err(_) => return Err(internal_error_response("Database error")),
    };

    if let Some(existing_release) = existing_release {
        return Ok(ReleaseUploadContext {
            release_id: existing_release.try_get("id").unwrap_or_default(),
            status: existing_release
                .try_get("status")
                .unwrap_or_else(|_| "quarantine".into()),
            published_at: existing_release
                .try_get("published_at")
                .unwrap_or_else(|_| Utc::now()),
            created: false,
        });
    }

    if !upload.can_start_release() {
        return Err(conflict_response(
            "Maven checksum and signature uploads require the target artifact to exist first",
        ));
    }

    let release = publish::make_release(package_id, upload, actor_user_id);
    let insert_result = sqlx::query(
        "INSERT INTO releases (id, package_id, version, status, published_by, description, changelog, is_prerelease, is_yanked, yank_reason, is_deprecated, deprecation_message, source_ref, provenance, published_at, updated_at) \
         VALUES ($1, $2, $3, 'quarantine', $4, $5, NULL, $6, false, NULL, false, NULL, NULL, $7, $8, $9)",
    )
    .bind(release.id)
    .bind(release.package_id)
    .bind(&release.version)
    .bind(release.published_by)
    .bind(&release.description)
    .bind(release.is_prerelease)
    .bind(&release.provenance)
    .bind(release.published_at)
    .bind(release.updated_at)
    .execute(db)
    .await;

    match insert_result {
        Ok(_) => Ok(ReleaseUploadContext {
            release_id: release.id,
            status: "quarantine".into(),
            published_at: release.published_at,
            created: true,
        }),
        Err(sqlx::Error::Database(db_error)) if db_error.is_unique_violation() => {
            let existing_release = sqlx::query(
                "SELECT id, status::text AS status, published_at \
                 FROM releases \
                 WHERE package_id = $1 AND version = $2",
            )
            .bind(package_id)
            .bind(&upload.version)
            .fetch_optional(db)
            .await
            .map_err(|_| internal_error_response("Failed to reload Maven release"))?
            .ok_or_else(|| internal_error_response("Failed to reload Maven release"))?;

            Ok(ReleaseUploadContext {
                release_id: existing_release.try_get("id").unwrap_or_default(),
                status: existing_release
                    .try_get("status")
                    .unwrap_or_else(|_| "quarantine".into()),
                published_at: existing_release
                    .try_get("published_at")
                    .unwrap_or_else(|_| Utc::now()),
                created: false,
            })
        }
        Err(_) => Err(internal_error_response("Failed to create Maven release")),
    }
}

async fn ensure_target_artifact_exists(
    db: &PgPool,
    release_id: Uuid,
    target_filename: &str,
    upload: &ParsedMavenUpload,
) -> Result<(), Response> {
    let exists = sqlx::query_scalar::<_, bool>(
        "SELECT EXISTS (SELECT 1 FROM artifacts WHERE release_id = $1 AND filename = $2)",
    )
    .bind(release_id)
    .bind(target_filename)
    .fetch_one(db)
    .await
    .map_err(|_| internal_error_response("Database error"))?;

    if exists {
        return Ok(());
    }

    let message = match upload.role {
        publish::MavenUploadRole::Checksum { .. } => {
            format!(
                "Checksum uploads require the target artifact '{}' to already exist",
                target_filename
            )
        }
        publish::MavenUploadRole::Signature { .. } => {
            format!(
                "Signature uploads require the target artifact '{}' to already exist",
                target_filename
            )
        }
        publish::MavenUploadRole::Primary | publish::MavenUploadRole::Pom => {
            format!("The target artifact '{}' does not exist", target_filename)
        }
    };

    Err(conflict_response(&message))
}

async fn apply_post_upload_updates(
    db: &PgPool,
    identity: &MavenIdentity,
    package_id: Uuid,
    release: &ReleaseUploadContext,
    upload: &ParsedMavenUpload,
    artifact_inserted: bool,
) -> Result<(), Response> {
    if upload.pom.is_some() {
        sqlx::query(
            "UPDATE packages \
             SET display_name = COALESCE($1, display_name), \
                 description = COALESCE($2, description), \
                 homepage = COALESCE($3, homepage), \
                 repository_url = COALESCE($4, repository_url), \
                 license = COALESCE($5, license), \
                 updated_at = NOW() \
             WHERE id = $6",
        )
        .bind(upload.pom_display_name())
        .bind(upload.pom_description())
        .bind(upload.pom_homepage())
        .bind(upload.pom_repository_url())
        .bind(upload.pom_primary_license())
        .bind(package_id)
        .execute(db)
        .await
        .map_err(|_| internal_error_response("Failed to update Maven package metadata"))?;
    } else if artifact_inserted {
        sqlx::query("UPDATE packages SET updated_at = NOW() WHERE id = $1")
            .bind(package_id)
            .execute(db)
            .await
            .map_err(|_| internal_error_response("Failed to update Maven package state"))?;
    }

    if upload.triggers_publication() {
        if matches!(release.status.as_str(), "quarantine" | "scanning") {
            sqlx::query(
                "UPDATE releases \
                 SET description = COALESCE($1, description), \
                     provenance = COALESCE($2, provenance), \
                     is_prerelease = $3, \
                     status = 'published', \
                     published_at = NOW(), \
                     updated_at = NOW() \
                 WHERE id = $4",
            )
            .bind(upload.pom_description())
            .bind(upload.pom_provenance())
            .bind(upload.pom.as_ref().is_some_and(|_| {
                upload.version.contains('-')
                    || upload
                        .version
                        .chars()
                        .any(|character| character.is_ascii_alphabetic())
            }))
            .bind(release.release_id)
            .execute(db)
            .await
            .map_err(|_| internal_error_response("Failed to publish Maven release"))?;

            let _ = sqlx::query(
                "INSERT INTO audit_logs (id, action, actor_user_id, actor_token_id, target_package_id, target_release_id, metadata, occurred_at) \
                 VALUES ($1, 'release_publish', $2, $3, $4, $5, $6, NOW())",
            )
            .bind(Uuid::new_v4())
            .bind(identity.user_id)
            .bind(identity.token_id)
            .bind(package_id)
            .bind(release.release_id)
            .bind(serde_json::json!({
                "ecosystem": "maven",
                "name": upload.package_name,
                "version": upload.version,
                "source": "maven_deploy",
                "group_id": upload.group_id,
                "artifact_id": upload.artifact_id,
            }))
            .execute(db)
            .await;
        } else {
            sqlx::query(
                "UPDATE releases \
                 SET description = COALESCE($1, description), \
                     provenance = COALESCE($2, provenance), \
                     updated_at = NOW() \
                 WHERE id = $3",
            )
            .bind(upload.pom_description())
            .bind(upload.pom_provenance())
            .bind(release.release_id)
            .execute(db)
            .await
            .map_err(|_| internal_error_response("Failed to update Maven release metadata"))?;
        }
    } else if artifact_inserted {
        sqlx::query("UPDATE releases SET updated_at = NOW() WHERE id = $1")
            .bind(release.release_id)
            .execute(db)
            .await
            .map_err(|_| internal_error_response("Failed to update Maven release state"))?;
    }

    Ok(())
}

fn release_accepts_new_artifacts(release: &ReleaseUploadContext) -> bool {
    match release.status.as_str() {
        "quarantine" | "scanning" => true,
        "published" => {
            release.published_at >= Utc::now() - Duration::hours(MAVEN_PUBLISH_GRACE_WINDOW_HOURS)
        }
        _ => false,
    }
}

async fn load_package_row(
    db: &PgPool,
    package_name: &str,
) -> Result<sqlx::postgres::PgRow, Response> {
    let normalized = normalize_package_name(package_name, &Ecosystem::Maven);
    sqlx::query(
        "SELECT p.id, p.visibility, p.owner_user_id, p.owner_org_id, \
                r.visibility::text AS repo_visibility, r.owner_user_id AS repo_owner_user_id, \
                r.owner_org_id AS repo_owner_org_id \
         FROM packages p \
         JOIN repositories r ON r.id = p.repository_id \
         WHERE p.ecosystem = 'maven' AND p.normalized_name = $1",
    )
    .bind(&normalized)
    .fetch_optional(db)
    .await
    .map_err(|_| internal_error_response("Database error"))?
    .ok_or_else(|| not_found_response("Artifact not found"))
}

async fn load_artifact_row(
    db: &PgPool,
    package_name: &str,
    version: &str,
    filename: &str,
) -> Result<sqlx::postgres::PgRow, Response> {
    let normalized = normalize_package_name(package_name, &Ecosystem::Maven);
    sqlx::query(
        "SELECT a.storage_key, a.content_type, a.sha256, p.id AS package_id, \
                p.visibility AS package_visibility, p.owner_user_id AS package_owner_user_id, \
                p.owner_org_id AS package_owner_org_id, \
                r.visibility::text AS repo_visibility, r.owner_user_id AS repo_owner_user_id, \
                r.owner_org_id AS repo_owner_org_id \
         FROM artifacts a \
         JOIN releases rel ON rel.id = a.release_id \
         JOIN packages p ON p.id = rel.package_id \
         JOIN repositories r ON r.id = p.repository_id \
         WHERE p.ecosystem = 'maven' AND p.normalized_name = $1 \
           AND rel.version = $2 \
           AND a.filename = $3 \
           AND rel.status IN ('published', 'deprecated', 'yanked') \
         ORDER BY rel.published_at DESC \
         LIMIT 1",
    )
    .bind(&normalized)
    .bind(version)
    .bind(filename)
    .fetch_optional(db)
    .await
    .map_err(|_| internal_error_response("Database error"))?
    .ok_or_else(|| not_found_response("Artifact not found"))
}

async fn authenticate_optional<S: MavenAppState>(
    state: &S,
    headers: &HeaderMap,
) -> Result<Option<MavenIdentity>, Response> {
    let token = extract_token(headers);
    let Some(token) = token else {
        return Ok(None);
    };
    authenticate_token(state, &token).await.map(Some)
}

async fn authenticate_publish_required<S: MavenAppState>(
    state: &S,
    headers: &HeaderMap,
) -> Result<MavenIdentity, Response> {
    let token = extract_bearer_token(headers).ok_or_else(|| {
        unauthorized_response("Authentication required for Maven deploy operations")
    })?;
    authenticate_token(state, &token).await
}

fn extract_token(headers: &HeaderMap) -> Option<String> {
    extract_bearer_token(headers).or_else(|| extract_basic_token(headers))
}

fn extract_bearer_token(headers: &HeaderMap) -> Option<String> {
    let authorization = headers.get(AUTHORIZATION)?.to_str().ok()?;
    let token = authorization.strip_prefix("Bearer ")?.trim();
    if token.is_empty() {
        None
    } else {
        Some(token.to_owned())
    }
}

fn extract_basic_token(headers: &HeaderMap) -> Option<String> {
    let authorization = headers.get(AUTHORIZATION)?.to_str().ok()?;
    let encoded = authorization.strip_prefix("Basic ")?;
    let decoded = BASE64_STANDARD.decode(encoded.trim()).ok()?;
    let decoded = String::from_utf8(decoded).ok()?;
    let (username, password) = decoded.split_once(':').unwrap_or((decoded.as_str(), ""));
    if password.starts_with("pub_") {
        return Some(password.to_owned());
    }
    if username.starts_with("pub_") {
        return Some(username.to_owned());
    }
    None
}

async fn authenticate_token<S: MavenAppState>(
    state: &S,
    token: &str,
) -> Result<MavenIdentity, Response> {
    if token.starts_with("pub_") {
        let token_hash = publaryn_core::security::hash_token(token);
        let row = sqlx::query(
            "SELECT id, user_id, scopes, expires_at, kind \
             FROM tokens \
             WHERE token_hash = $1 AND is_revoked = false",
        )
        .bind(&token_hash)
        .fetch_optional(state.db())
        .await
        .map_err(|_| internal_error_response("Database error"))?
        .ok_or_else(|| unauthorized_response("Invalid or revoked token"))?;

        let token_kind: String = row.try_get("kind").unwrap_or_default();
        if token_kind == "oidc_derived" {
            return Err(unauthorized_response(
                "OIDC-derived tokens are not valid for Maven access",
            ));
        }

        let expires_at = row
            .try_get::<Option<DateTime<Utc>>, _>("expires_at")
            .unwrap_or(None);
        if expires_at.is_some_and(|expires_at| expires_at <= Utc::now()) {
            return Err(unauthorized_response("Token has expired"));
        }

        let user_id = row
            .try_get::<Option<Uuid>, _>("user_id")
            .unwrap_or(None)
            .ok_or_else(|| unauthorized_response("Token is not associated with a user"))?;
        let token_id: Option<Uuid> = row.try_get("id").ok();
        let scopes: Vec<String> = row.try_get("scopes").unwrap_or_default();

        if let Some(token_id) = token_id {
            let _ = sqlx::query("UPDATE tokens SET last_used_at = NOW() WHERE id = $1")
                .bind(token_id)
                .execute(state.db())
                .await;
        }

        return Ok(MavenIdentity {
            user_id,
            token_id,
            scopes,
        });
    }

    let claims = publaryn_auth::validate_token(token, state.jwt_secret(), state.jwt_issuer())
        .map_err(|_| unauthorized_response("Invalid or expired token"))?;
    let user_id =
        Uuid::parse_str(&claims.sub).map_err(|_| unauthorized_response("Invalid token subject"))?;
    let token_id = Uuid::parse_str(&claims.jti).ok();

    Ok(MavenIdentity {
        user_id,
        token_id,
        scopes: claims.scopes,
    })
}

fn has_scope(identity: &MavenIdentity, scope: &str) -> bool {
    identity.scopes.iter().any(|candidate| candidate == scope)
}

async fn package_readable(
    package_row: &sqlx::postgres::PgRow,
    db: &PgPool,
    actor_user_id: Option<Uuid>,
) -> bool {
    can_read_package(
        db,
        &package_row
            .try_get::<String, _>("visibility")
            .unwrap_or_default(),
        &package_row
            .try_get::<String, _>("repo_visibility")
            .unwrap_or_default(),
        package_row.try_get("owner_user_id").unwrap_or(None),
        package_row.try_get("owner_org_id").unwrap_or(None),
        package_row.try_get("repo_owner_user_id").unwrap_or(None),
        package_row.try_get("repo_owner_org_id").unwrap_or(None),
        actor_user_id,
    )
    .await
}

async fn artifact_readable(
    artifact_row: &sqlx::postgres::PgRow,
    db: &PgPool,
    actor_user_id: Option<Uuid>,
) -> bool {
    can_read_package(
        db,
        &artifact_row
            .try_get::<String, _>("package_visibility")
            .unwrap_or_default(),
        &artifact_row
            .try_get::<String, _>("repo_visibility")
            .unwrap_or_default(),
        artifact_row
            .try_get("package_owner_user_id")
            .unwrap_or(None),
        artifact_row.try_get("package_owner_org_id").unwrap_or(None),
        artifact_row.try_get("repo_owner_user_id").unwrap_or(None),
        artifact_row.try_get("repo_owner_org_id").unwrap_or(None),
        actor_user_id,
    )
    .await
}

async fn has_package_write_access(
    db: &PgPool,
    package_id: Uuid,
    repository_id: Uuid,
    owner_user_id: Option<Uuid>,
    owner_org_id: Option<Uuid>,
    actor_user_id: Uuid,
) -> bool {
    if owner_user_id == Some(actor_user_id) {
        return true;
    }

    if let Some(org_id) = owner_org_id {
        let roles = ORG_PACKAGE_WRITE_ROLES
            .iter()
            .map(|role| (*role).to_owned())
            .collect::<Vec<_>>();
        let direct_access = sqlx::query_scalar::<_, bool>(
            "SELECT EXISTS (\
                 SELECT 1 \
                 FROM org_memberships \
                 WHERE org_id = $1 AND user_id = $2 AND role::text = ANY($3)\
             )",
        )
        .bind(org_id)
        .bind(actor_user_id)
        .bind(&roles)
        .fetch_one(db)
        .await
        .unwrap_or(false);

        if direct_access {
            return true;
        }

        let package_permissions = TEAM_PACKAGE_PUBLISH_PERMISSIONS
            .iter()
            .map(|permission| (*permission).to_owned())
            .collect::<Vec<_>>();
        let team_package_access = sqlx::query_scalar::<_, bool>(
            "SELECT EXISTS (\
                 SELECT 1 \
                 FROM team_package_access tpa \
                 JOIN team_memberships tm ON tm.team_id = tpa.team_id \
                 JOIN teams t ON t.id = tpa.team_id \
                 JOIN packages p ON p.id = tpa.package_id \
                 WHERE tpa.package_id = $1 \
                   AND tm.user_id = $2 \
                   AND t.org_id = p.owner_org_id \
                   AND tpa.permission::text = ANY($3)\
             )",
        )
        .bind(package_id)
        .bind(actor_user_id)
        .bind(&package_permissions)
        .fetch_one(db)
        .await
        .unwrap_or(false);

        if team_package_access {
            return true;
        }

        let repository_permissions = TEAM_REPOSITORY_PUBLISH_PERMISSIONS
            .iter()
            .map(|permission| (*permission).to_owned())
            .collect::<Vec<_>>();
        let team_repository_access = sqlx::query_scalar::<_, bool>(
            "SELECT EXISTS (\
                 SELECT 1 \
                 FROM team_repository_access tra \
                 JOIN team_memberships tm ON tm.team_id = tra.team_id \
                 JOIN teams t ON t.id = tra.team_id \
                 JOIN repositories r ON r.id = tra.repository_id \
                 WHERE tra.repository_id = $1 \
                   AND tm.user_id = $2 \
                   AND t.org_id = r.owner_org_id \
                   AND tra.permission::text = ANY($3)\
             )",
        )
        .bind(repository_id)
        .bind(actor_user_id)
        .bind(&repository_permissions)
        .fetch_one(db)
        .await
        .unwrap_or(false);

        return team_repository_access;
    }

    false
}

#[allow(clippy::too_many_arguments)]
async fn can_read_package(
    db: &PgPool,
    pkg_visibility: &str,
    repo_visibility: &str,
    pkg_owner_user_id: Option<Uuid>,
    pkg_owner_org_id: Option<Uuid>,
    repo_owner_user_id: Option<Uuid>,
    repo_owner_org_id: Option<Uuid>,
    actor_user_id: Option<Uuid>,
) -> bool {
    let pkg_anonymous = matches!(pkg_visibility, "public" | "unlisted");
    let repo_anonymous = matches!(repo_visibility, "public" | "unlisted");

    if pkg_anonymous && repo_anonymous {
        return true;
    }

    let Some(actor) = actor_user_id else {
        return false;
    };

    let pkg_access = is_owner_or_member(db, pkg_owner_user_id, pkg_owner_org_id, actor).await;
    let repo_access = is_owner_or_member(db, repo_owner_user_id, repo_owner_org_id, actor).await;

    (pkg_anonymous || pkg_access) && (repo_anonymous || repo_access)
}

async fn is_owner_or_member(
    db: &PgPool,
    owner_user_id: Option<Uuid>,
    owner_org_id: Option<Uuid>,
    actor_user_id: Uuid,
) -> bool {
    if owner_user_id == Some(actor_user_id) {
        return true;
    }

    if let Some(org_id) = owner_org_id {
        let result = sqlx::query_scalar::<_, bool>(
            "SELECT EXISTS (SELECT 1 FROM org_memberships WHERE org_id = $1 AND user_id = $2)",
        )
        .bind(org_id)
        .bind(actor_user_id)
        .fetch_one(db)
        .await;
        return result.unwrap_or(false);
    }

    false
}

fn not_found_response(message: &str) -> Response {
    (StatusCode::NOT_FOUND, message.to_owned()).into_response()
}

fn unauthorized_response(message: &str) -> Response {
    (StatusCode::UNAUTHORIZED, message.to_owned()).into_response()
}

fn forbidden_response(message: &str) -> Response {
    (StatusCode::FORBIDDEN, message.to_owned()).into_response()
}

fn bad_request_response(message: &str) -> Response {
    (StatusCode::BAD_REQUEST, message.to_owned()).into_response()
}

fn conflict_response(message: &str) -> Response {
    (StatusCode::CONFLICT, message.to_owned()).into_response()
}

fn internal_error_response(message: &str) -> Response {
    (StatusCode::INTERNAL_SERVER_ERROR, message.to_owned()).into_response()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_sha256_route_uses_artifact_parser() {
        let parsed = parse_artifact_path("com/example/demo/1.0.0/demo-1.0.0.jar").unwrap();
        assert_eq!(parsed.1, "demo");
        assert_eq!(parsed.2, "1.0.0");
    }
}
